### ISSUE TITLE
additional data on Emoji Click ?

### ISSUE THREAD

**Issue by adamprocter** [wobsoriano/vuemoji-picker#2]
Is it possible to get additional data into moment you click the emoji the like this ? @emojiClick="handleEmojiClick(detail, nodeinfo)" 
I am iterating over objects and would be useful to add some of my own data when the emoji is clicked ?
I tried to write as two method calls on the click but that didn't seem to work.
Thanks again

**Comment by wobsoriano** [comment]
```html
<VuemojiPicker @emojiClick="$event => handleEmojiClick($event, nodeinfo)" />
```

**Comment by adamprocter** [comment]
Thank you again.
