### ISSUE TITLE
 I made a Chinese document

### ISSUE THREAD

**Issue by JuYiYang** [wobsoriano/vuemoji-picker#9]
[vuemoji-picker API中文文档.md](https://github.com/wobsoriano/vuemoji-picker/files/9637773/vuemoji-picker.API.md)

**Comment by newproplus** [comment]
You can create a `Pull retuest` to merge your code.

**Comment by JuYiYang** [comment]
> 您可以创建一个`Pull retuest`合并您的代码。

I don't have push permission

**Comment by newproplus** [comment]
@JuYiYang 

Not `push` your code to this repo.

1. At first,you should `fork` this repo to your own repo.
2. Then,commit and push your code to your own repo.
3. At last,create a `Pull request` from your own repo to this repo.
